version: '3.7'

services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile.prod
    command: gunicorn relief_ops_manager.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/static
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.1
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
    - ./.env-db.prod
  
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
    ports:
      - 1337:80
    depends_on:
      - web
    
volumes:
  postgres_data:
  static_volume: