# Generated by Django 3.0.4 on 2020-03-30 13:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('relief_efforts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_no', models.CharField(blank=True, max_length=10, null=True)),
                ('building_name', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.TextField()),
                ('brgy', models.TextField()),
                ('city_municipality', models.TextField()),
                ('province', models.TextField()),
                ('region', models.TextField()),
                ('postal_code', models.TextField()),
                ('update_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Address Details',
                'ordering': ('-update_date',),
            },
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Bank Details',
                'ordering': ('-update_date',),
            },
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.TextField()),
                ('update_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Details',
                'ordering': ('-update_date',),
            },
        ),
        migrations.CreateModel(
            name='ItemizedNeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_item', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('received_inventories', models.IntegerField(default=0)),
                ('total_need', models.IntegerField(default=0)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Itemized Needs',
                'ordering': ('-update_date',),
            },
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=999)),
                ('severity_urgency', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], default='low', max_length=50)),
                ('status', models.CharField(default='unverified', max_length=50)),
                ('org_type', models.CharField(choices=[('hospital', 'hospital'), ('organization', 'organization'), ('business', 'business'), ('supplier', 'supplier'), ('research', 'research'), ('facility', 'facility'), ('lgu', 'lgu'), ('personal', 'personal'), ('other', 'other')], default='other', max_length=50)),
                ('relief_type', models.CharField(choices=[('frontliner', 'frontliner'), ('families', 'families'), ('public', 'public'), ('supplier', 'supplier'), ('testing kit for PUI', 'testing kit for PUI'), ('other service personel', 'other service personel'), ('other', 'other')], default='other', max_length=999)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Organizations',
                'ordering': ('-update_date',),
            },
        ),
        migrations.CreateModel(
            name='OtherDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what_they_do', models.TextField(default='N/A')),
                ('who_they_help', models.TextField(default='N/A')),
                ('link_for_more_info', models.TextField(default='N/A')),
                ('link_to_poster', models.TextField(default='N/A')),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relief_efforts.Organizations')),
            ],
            options={
                'verbose_name_plural': 'Other Details',
                'ordering': ('-update_date',),
            },
        ),
        migrations.CreateModel(
            name='PricingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_item', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('unit_price', models.CharField(max_length=100)),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relief_efforts.Organizations')),
            ],
            options={
                'verbose_name_plural': 'Pricing Details',
                'ordering': ('-update_date',),
            },
        ),
        migrations.DeleteModel(
            name='ReliefEfforts',
        ),
        migrations.AddField(
            model_name='itemizedneeds',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relief_efforts.Organizations'),
        ),
        migrations.AddField(
            model_name='contactdetails',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relief_efforts.Organizations'),
        ),
        migrations.AddField(
            model_name='bankdetails',
            name='contact_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relief_efforts.ContactDetails'),
        ),
        migrations.AddField(
            model_name='addressdetails',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relief_efforts.Organizations'),
        ),
    ]
